services:
  # VSB Django Backend Web Service
  - type: web
    name: vsb-portal-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn vsb_project.wsgi:application"
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: DB_HOST
        value: "" # User to fill with their online database host URL (e.g. Aiven)
      - key: DB_USER
        value: "root" # User to fill with their online database username
      - key: DB_PASSWORD
        value: "" # User to fill with their online database password
      - key: DB_NAME
        value: "vsb_db" # User to fill with database name
      - key: DB_PORT
        value: "3306"
