# Generated by Django 5.0.7 on 2026-07-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hod_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('register_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('community', models.CharField(blank=True, max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhaar', models.CharField(blank=True, max_length=30, null=True)),
                ('raw_aadhaar', models.CharField(blank=True, max_length=30, null=True)),
                ('residence', models.CharField(blank=True, max_length=30, null=True)),
                ('hometown', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_admission', models.CharField(blank=True, max_length=20, null=True)),
                ('mode_of_admission', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_quota', models.CharField(blank=True, max_length=50, null=True)),
                ('regulation', models.CharField(blank=True, max_length=20, null=True)),
                ('emis_no', models.CharField(blank=True, max_length=50, null=True)),
                ('tamil_medium', models.CharField(blank=True, max_length=20, null=True)),
                ('physically_challenged', models.CharField(blank=True, max_length=20, null=True)),
                ('sslc', models.CharField(blank=True, max_length=100, null=True)),
                ('hsc', models.CharField(blank=True, max_length=100, null=True)),
                ('diploma', models.CharField(blank=True, max_length=100, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=20, null=True)),
                ('arrears', models.IntegerField(default=0)),
                ('photo_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhaar_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('sslc_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('hsc_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('certificates_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=True)),
                ('profile_completion', models.IntegerField(default=50)),
                ('transport', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_route', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=10, null=True)),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.IntegerField(default=1)),
                ('skills', models.TextField(default='[]')),
                ('languages', models.TextField(default='[]')),
                ('internships', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('hackathons', models.IntegerField(default=0)),
                ('certificates', models.IntegerField(default=0)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('github', models.CharField(blank=True, max_length=255, null=True)),
                ('leetcode', models.CharField(blank=True, max_length=255, null=True)),
                ('placement_status', models.CharField(default='Not Applied', max_length=50)),
                ('placement_company', models.CharField(blank=True, max_length=100, null=True)),
                ('placement_package', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.CharField(default='Today', max_length=50)),
                ('mysql_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
